#!/bin/bash
#Purpose: automatically add offenders IPs to ufw deny rule
#  It scans error.log and access.log for "not found or unable to stat" and 404 respectably. 
#  When find IPs with occurance > nMax will add rull to ufw deny rule.
#  Save in /usr/local/bin/banip, chmod +x it, and schedule add to crontab the follow:
#  ban IPs with excesss number of 404
#  */10 * * * * /usr/local/bin/banip
#  You check log:
#  cat /var/log/banIP.log to see last run or 
#  cat /var/log/banips.log to see banned IPs

#ban IPs:
bip() {
cat $cTarget | while read line
do
 ip=$(echo $line | cut -d '.' -f 1,2,3)
 if [ $ip != "192.168.1" ]
  then
   echo $line >> $cBanLog
   echo "Inserting $line :"  >> $cBanIpLog
   /usr/sbin/ufw insert 1 deny from $line to any  >> $cBanIpLog
   /usr/sbin/ufw insert 1 deny to $line from any >> $cBanIpLog
  #echo "       Banned $line" >> $cBanIpLog
  fi
done
}



nMax=10 # Maximum failes
cTarget="/tmp/_ban.ip" # Temporary storage file
cLogFile="/var/log/apache2/access.log" # apache2 access log file
cLogFile1="/var/log/apache2/error.log" # apache2 error.log

cBanLog="/var/log/banips.log" #This script log file
cBanIpLog="/var/log/banIP.log"
ignorIP="192.168.1" #IP to ignor, usually home network

echo "Banning IP run at $(date)
Maximum offends: $nMax
Checking logs
        $cLogFile
        $cLogFile1
        " > $cBanIpLog

#Get the bastards out of apache2 access log:
grep 404 $cLogFile | cut -d ' ' -f 1,4 | cut -d ':' -f 1,2,3 | tr -d '[' | sort | uniq -c | sort -rn | awk ' $1 > '"$nMax"' {print $2}' | uniq -c | awk '{print $2}' > $cTarget

#Banning
bip

#Get the bastards out of apache2 error log:
grep "not found or unable to stat" $cLogFile1 | awk '{print $1,$2,$3,$5,$10}' | cut -d ':' -f 1 | sort | uniq -c | awk ' $1 > '"$nMax"' {print $6}' > $cTarget

#Banning
bip

#Conclude:
/bin/systemctl restart ufw
/bin/systemctl status ufw >> $cBanIpLog
/usr/sbin/ufw status >> $cBanIpLog
cat $cBanLog | sort | uniq > /var/log/banips.tmp >> $cBanIpLog
rm /var/log/banips.log
mv /var/log/banips.tmp $cBanLog
cat $cBanLog >> $cBanIpLog
echo "Log file at $cBanIpLog
Finished banning $(date)
